export 'auth/index.dart';
export 'dashboard/index.dart';
export 'food_recognition/index.dart';
export 'health_calculator/index.dart';
export 'login/index.dart';
export 'practice/index.dart';
export 'profile/index.dart';
export 'register/index.dart';
export 'workout/index.dart';
